pipeline {
    agent any

    environment {
        TF_IN_AUTOMATION           = "true"
        TF_INPUT                    = "false"
        ANSIBLE_HOST_KEY_CHECKING   = "False"
    }

    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/funmicra/Mini-SaaS.git',
                    branch: 'master'
                )
            }
        }

        stage('Terraform Apply') {
            when {
                expression {
                    currentBuild.changeSets.any { cs ->
                        cs.items.any { it.msg.contains("[INFRA]") }
                    }
                }
            }
            environment {
                AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
                AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
            }
            steps {
                sh 'python3 scripts/terraform_apply.py'
            }
        }

        stage('Terraform Destroy') {
            when {
                expression {
                    currentBuild.changeSets.any { cs ->
                        cs.items.any { it.msg.contains("[DESTROY]") }
                    }
                }
            }
            environment {
                AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
                AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
            }
            steps {
                script {
                    echo "[INFO] [DESTROY] commit detected. Running terraform destroy..."
                    sh '''
                        cd terraform
                        terraform destroy -auto-approve
                    '''

                    echo "[INFO] Pipeline terminating after Terraform destroy."
                    env.TERMINATE_PIPELINE = 'true'
                    echo "[INFO] Pipeline will terminate after Terraform destroy."
                }
            }
        }
        

        stage('Create Dynamic Ansible Inventory') {
            when {
                expression { 
                    // skip if pipeline was terminated
                    env.TERMINATE_PIPELINE != 'true' 
                }
            }
            steps {
                script {
                    sh 'python3 scripts/create_dynamic_inventory.py'
                }
            }
        } 
        
        stage('Configuring with Ansible') {
            when {
                expression { 
                    // skip if pipeline was terminated
                    env.TERMINATE_PIPELINE != 'true' 
                }
            }
            steps {
                withCredentials([
                    sshUserPrivateKey(
                        credentialsId: 'ANSIBLE_PRIVATE_KEY',
                        keyFileVariable: 'ANSIBLE_PRIVATE_KEY'
                        // usernameVariable: 'ANSIBLE_USER'
                    )
                ]) {
                    sh 'python3 scripts/run_ansible_playbook.py'
                }
            }
        }

        stage('Announce SSH login Commands') {
            when {
                expression { 
                    // skip if pipeline was terminated
                    env.TERMINATE_PIPELINE != 'true' 
                }
            }
            steps {
                sh 'python3 scripts/announce_ssh_commands.py'
            }
        }    
    }

    post {
        success {
            echo 'Infrastructure provisioned and configured successfully.'
        }
        failure {
            echo 'Pipeline failed. Inspect Terraform or Ansible stage logs.'
        }
    }
}
